name: imports
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: roshedgostaran <roshedgostarandev1@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
